Add Pending Interaction Notification
leonardo-barbosa/perry-the-bot pull request #10
Opened 2017-12-16 01:29 UTC by vagnervst

2017-12-18 19:15 UTC, leonardo-barbosa requested changes

2017-12-18 19:15 UTC, leonardo-barbosa commented on Class/ZendeskConnection.py
> +        def notify_pending_interaction_tickets(self):
Identação

2017-12-18 19:15 UTC, leonardo-barbosa commented on Class/ZendeskConnection.py
> +            if diff_in_hours >= inactiveHours
Dois pontos

2017-12-18 19:15 UTC, leonardo-barbosa commented on Class/ZendeskConnection.py
> +                mongoSup = [sup for sup in supporters if sup["zendesk_id"] == ticket.assignee_id]
Não iterável

2017-12-19 03:00 UTC, vagnervst commented
@leonardo-barbosa changes implemented!

2017-12-19 12:14 UTC, leonardo-barbosa approved these changes
PNM!

2017-12-19 13:16 UTC, merged